name: acsefunctions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # Use a general version instead of a specific build
  - numpy
  - scipy
  - flake8
  - pytest
  - pip
  - pip:
      - -r requirements.txt  # Use pip to install packages listed in requirements.txt